### ISSUE TITLE
The existing text should be displayed in an text input

### ISSUE THREAD

**Issue by ulf1** [linguistik/tonbeleg#170]
![iMarkup_20220121_083906.jpg](https://user-images.githubusercontent.com/8018044/150486164-84b00109-5852-4d3f-af54-7059f58f08f7.jpg)

(If you coded a vue component, you need `props`)

**Comment by nickl1234567** [comment]
@ulf1 Soll der Text als Wert drin stehen, sodass der Text geändert werden kann, oder soll der Text nur als Platzhalter drin stehen?

**Comment by nickl1234567** [comment]
der Text soll drin stehen, sodass man das direkt ändern kann. So ist es aktuell.
