### ISSUE TITLE
upload data

### ISSUE THREAD

**Issue by nickl1234567** [linguistik/tonbeleg#21]
tonaufnahme zum hochladen markieren

**Comment by matzienski** [comment]
Tonaufnahme ist markiert und im Recording gespeichert. Upload ist allerdings noch nciht erfolgt.

**Comment by matzienski** [comment]
Upload findet statt allerdings wird das array immer ersetzt. Das mit dem Updaten funktioniert noch nicht

**Comment by matzienski** [comment]
Mit meta Daten hochladen
