### ISSUE TITLE
CSS in recording

### ISSUE THREAD

**Issue by nickl1234567** [linguistik/tonbeleg#29]
wenn das fenster, welches das recording anzeigt verkleinert wird, so wird das recording sehr klein und die knöpfe überdecken den text.
sinnvoll wäre es dann das recording nach unten größer zu machen, damit alle informationen weiterhin sichtbar sind.

**Comment by matzienski** [comment]
ich hab so icons eingefügt und das dropdown weg dann gehts eig egal wie groß das ist
