### ISSUE TITLE
alle daten löschen

### ISSUE THREAD

**Issue by nickl1234567** [linguistik/tonbeleg#30]
implementierung eines knopfes, der alle daten oder nur alle aufnahmen löscht.
am besten in den einstellungen 2 knöpfe mit den entsprechenden funktionalitäten implementieren.
Zu beachten ist, dass alle ordner und alle dateien rekursiv gelöscht werden soll. es sollten keine dateien oder ordner übrig bleiben

**Comment by matzienski** [comment]
Dann hat man ja 3 Knöpfe Daten, Recordings, und Acc löschen. Keine Ahnung was da am schlausten ist

**Comment by nickl1234567** [comment]
ja. also halte alle bis auf daten löschen für sinnvoll, also warum sollte man seine daten löschen wollen ohne den account zu löschen?

**Comment by matzienski** [comment]
ja genau seh ich auch so. Perfekt dann so

**Comment by matzienski** [comment]
auf dem server muss noch gelöscht werden. Mit real time und anderer datenbank muss man aufpassen
