### ISSUE TITLE
upload/load personal data

### ISSUE THREAD

**Issue by nickl1234567** [linguistik/tonbeleg#58]
persönliche daten auf server speichern und laden

**Comment by BetaZebra** [comment]
sollte jetzt gehen wär cool wenn das wer anders mal bei ihm testet

**Comment by McBattery** [comment]
Ja geht

**Comment by nickl1234567** [comment]
geht nicht mehr. ich glaube das laden der lokalen daten überschreibt die daten von der firebase. dadurch ist es quasi unmöglich einstellungen zu setzen und persistent zu speichern

**Comment by BetaZebra** [comment]
Ich sehe das Problem nicht, Natürlich überschreiben die lokalen Daten die Daten in der Firebase. Aber wieso wird es dadurch unmöglich Einstelungen zu machen??

**Comment by nickl1234567** [comment]
ich habe nicht ausgiebig getestet, aber ich glaube ich habe auf dem handy und auf dem computer verschiedene einstellungen, obwohl ich den selben account verwende

**Comment by BetaZebra** [comment]
Jaja, aber das Problem haben wir durchgehend in der App. Bis jetzt sind wir davon ausgegangen dass ein User ein Handy hat. Das ist nicht kapputt das Feature ist einfach nicht dafür da

**Comment by nickl1234567** [comment]
dann machen wir irgendwas falsch herum. ursprünglich wollten wir eine webapp mit offline funktionalitäten bauen. gerade ist es eine offline app mit web funktionalitäten

**Comment by BetaZebra** [comment]
hä

**Comment by BetaZebra** [comment]
was willst du mir dam it sagen? Die App soll vollständig offline funktionieren, also bin ich davon ausgegangen, dass ich offline auch mein Profil ändern kann, um das hinterher zu aktualisieren in der Datenbank. Egal wie rum man das macht, eine Seite wird immer überschrieben. Falls das nen Problem für dich ist mach nen neuen Issue auf

**Comment by BetaZebra** [comment]
Ich kann auch implementieren, dass er sich die Daten der letze Änderungen abspeichert für jedes einzelne Feld und dann die richtigen läd, aber das ist übelster aufwand und zur Zeit auch glaub ich nicht das wichtigste.

**Comment by nickl1234567** [comment]
ja stimmt. da muss man sich etwas überlegen. wahrscheinlich wäre ein timestamp sinnvoll, der angibt, wann die daten geändert wurden und dann wird immer das neuste verwendet und lokal sowie in firestore gespeichert

**Comment by BetaZebra** [comment]
mach ich wenn ich zeit hab so, aber jetzt nicht mehr vor der winterpause, ist ja auch nicht kritisch für ander funktionalitäten
