### ISSUE TITLE
add multiple language input

### ISSUE THREAD

**Issue by nickl1234567** [linguistik/tonbeleg#64]
user should be able to add multiple first and multiple second languages

**Comment by BetaZebra** [comment]
werdem jetzt korrekt gespeichert und auch wieder geladen. Würde auch gleiches für jobs machen, da man auch mehrer hat

**Comment by BetaZebra** [comment]
ich mach noch code cleanup dann push ich das morgen

**Comment by BetaZebra** [comment]
sprachen müssen untereinander angezeigt werden nicht nebeneinander sonst kann man das nicht auf nem handy

**Comment by nickl1234567** [comment]
seit wann ist das denn nicht mehr untereinander? wenn ich das ausführe, sieht das bei mir so aus:
![image](https://user-images.githubusercontent.com/46937156/145559450-e3531096-aa1e-4d97-8bcf-ed9f719b8871.png)

**Comment by nickl1234567** [comment]
@BetaZebra scheibar ist bei einem deiner commits das multipleElements Component kaputt gegangen. wenn du nichts dagegen hast, würde ich das gerne auf einen früheren commit zurücksetzen

**Comment by BetaZebra** [comment]
Was meinst du mit kaputt? Bei mir Jan und Markus hat alles funktioniert. Und bei uns stehen die nebeneinander

**Comment by BetaZebra** [comment]
ich close den mal, weil er sich doppelt
