### ISSUE TITLE
Types bei user settings

### ISSUE THREAD

**Issue by BetaZebra** [linguistik/tonbeleg#76]
wenn man zipcode oder alter leer lässt und speichert konvertiert der das intern zu nem string und speichert dieses als string ab, läd den auch als string in die datenbank. Beim wiederladen werden allerdings fehler geworfen weil der typ offensichtlich falsch ist(allerdings nur manchmal wirft er fehler). Ich kann aber nach nem Input nicht testen ob der daraus nen string gemacht hat oder das Feld leer ist, weil er mir beim vergleich erlärt, dass kann gar kein string sein, da der typ ja als number definiert ist.

**Comment by BetaZebra** [comment]
Wir können natürlich zipCode und age generell als String speichern, fänd ich aber ziemlich unelegant

**Comment by nickl1234567** [comment]
was ist mit 
if(zipcode == 0){
zipcodeString = "0";
}
und entsprechend
if(zipCodeString == "0"){
zipCode = 0;
}
